version: "3.9"

services:
  redis:
    image: redis:alpine
    entrypoint: redis-server --requirepass 0123456789
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    mem_limit: 512m
    cpus: 0.5

volumes:
  redis-data:
